SELECT * FROM customer LIMIT 5;

--What is the total revenue generated by male versus female customers?
SELECT gender, SUM(purchase_amount)
FROM customer
GROUP BY gender;


--Which customers used a discount but still spent more than the overall average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >=(SELECT 
AVG(purchase_amount) FROM customer);


-- What are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating)::numeric, 2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;


-- Compare the average purchase amount between 'Standard' and 'Express' shipping types. Which one is higher?
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Do subscribed customers spend more? Compare the total revenue and average spend between subscribers and non-subscribers.
SELECT subscription_status, 
COUNT(customer_id) AS total_customers, 
ROUND(AVG(purchase_amount), 2) AS avg_spend, 
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- What are the top 3 most purchased products within each specific category?
WITH item_counts AS (
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Are customers who are "repeat buyers" (having more than 5 previous purchases) also likely to be subscribed?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- What is the total revenue generated by each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;